### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [czerlun/Chess_endgame#1]
Dziękuję za link do repozytorium. Jeśli sam Pan sobie zmienił temat projektu i powiadomił mnie o tym w połowie maja, to czy prosząc o wyjawienie mi nowego tematu (w `README.md`) nie nadużywam Pana uprzejmości?

**Comment by czerlun** [comment]
Dodałem proszę Pana opis projektu do README.md. Proszę o do dalsze uwagi.

**Comment by MarcinCiura** [comment]
Dziękuję za `README.md`. W obecnym stanie program — oprócz rysowania na ekranie — zawiera jedną nietrywialną metodę `move_is_possible()`, a i ona składa się z 8 kopii podobnych 5-wierszowych fragmentów. To trochę za mało na pokaz Pana umiejętności.

Co by Pan powiedział na program do grania w szachy dla dwojga ludzkich graczy? Na wyglądzie zupełnie mi nie zależy, może być po każdym ruchu wypisywana przez `print()` nowa szachownica z figurami KHGSWP dla białych i khgswp dla czarnych, a ruchy podawane przez ludzi w [długiej notacji algebraicznej](https://pl.wikipedia.org/wiki/Szachowa_notacja_algebraiczna#Odmiany_notacji). Chodzi tylko o to, żeby program nie dopuszczał nieprawidłowych ruchów.

Ewentualnie możemy ustalić jeszcze coś innego. Może też Pan wziąć coś z listy dra Gąciarza.

**Comment by MarcinCiura** [comment]
Co Pan wybrał? Proszę o wiadomość.
